plugin: amazon.aws.aws_ec2
regions:
  - us-east-1
keyed_groups:
  - key: tags.role
    prefix: role
filters:
  instance-state-name: running
hostnames:
  - public-ip-address
  - dns
compose:
  ansible_host: public_ip_address
vars:
  ansible_ssh_private_key_file: ~/.ssh/id_rsa  # Path to your private key
cache: false

