plugin: amazon.aws.aws_ec2
regions:
  - us-east-1
keyed_groups:
  - key: tags.role
    prefix: role
filters:
  instance-state-name: running
compose:
  ansible_host: public-ip-address
cache: false
hostnames:
  - dns
