name: TerraformAnsibleRun

on:
  workflow_dispatch:

jobs:
  terraform-ansible-run:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Terraform
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: '1.13.4'

      # Step 3: Terraform Init
      - name: Terraform Init
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
        run: cd Terraform && terraform init

      # Step 4: Terraform Apply (without manual approval)
      - name: Terraform Apply
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
        run: cd Terraform && terraform apply -auto-approve

      # Step 5: Set up Ansible
      - name: Set up Ansible
        run: sudo apt-get install -y ansible

      # Step 6: Set up SSH Private Key for Ansible
      - name: Set up SSH Private Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      # Step 7: Run Ansible Playbook
      - name: Run Ansible Playbook
        run: ansible-playbook -i Ansible/aws_ec2.yml Ansible/site.yml


